### ISSUE TITLE
question about "number of registers"

### ISSUE THREAD

**Issue by i-Taozi** [microsoft/ArchProbe#8]
For the [reg_count](https://github.com/microsoft/ArchProbe/blob/main/apps/archprobe/app.cpp#L165) method, I have a doubt
The comments for Step1 are as follows:
```cpp
     // Step 1. Probe for the most number of registers we can use by activating
     // different numbers of threads to try to use up all the register resources.
     // In case of register spill the kernel latency would surge.
     //
     // The group size was kept 1 to minimize the impact of scheduling.
```
But the code of Step1 shows that the currently measured `nreg_max` is the maximum number of registers available to the kernel when the number of threads remains 1
```cpp
uint32_t nreg = NREG_MIN;
for (; nreg <= NREG_MAX; nreg += NREG_STEP) {
         double time = bench(1, 1, nreg);
         //....
}
```
In addition, according to the following sections, we can know that nreg_max will not exceed 512. According to the description in the paper, I guess that nreg_max is 181 measured on Adreno 640.
```cpp
  const uint32_t NREG_MIN = env.cfg_num("NRegMin", 1);
  const uint32_t NREG_MAX = env.cfg_num("NRegMax", 512);
  const uint32_t NREG_STEP = env.cfg_num("NRegStep", 1);
```
-------
My question is: Is the purpose of step1 to probe the maximum number of available registers on a single thread - `nreg_max`

If yes, I think the comments of step1 is not quite correct and will lead to misunderstanding.
And I want to know that on Adreno 640, since there is a 384 x 181 shared 32bit-register pool, why the maximum number of available registers for a single thread is 181, is it related to the allocation strategy of the pool?

If not, is the value of nreg_max 384 x 181?

**Comment by i-Taozi** [comment]
```json
    "RegCount": {
        "Done": true,
        "FullRegConcurWorkgroupCount": 12,
        "HalfRegConcurWorkgroupCount": 24,
        "RegCount": 183,
        "RegType": "Pooled"
    },
```
According to [adreno640/Google_Pixel_4/ArchProbeReport.json](https://github.com/microsoft/ArchProbe/blob/main/examples/adreno640/Google_Pixel_4/ArchProbeReport.json#L71), Does this mean "It shows a 24×183 shared 32b-register pool."？

This number is very different from the 384 x 181 mentioned in the paper.

**Comment by PENGUINLIONG** [comment]
Thanks for your comment. If I understand it correctly you are confused why the *pooled* registers are not shared among *all threads* (any physical ALU has access to all register) but, rather, *per physical ALU* (any physical ALU only has access to its own 181 regsiters).

The number 384 is the number of **all physical ALUs** on chip, and there are 3 SMs contributing to this number so the registers doesn't share across SM boundary. They are isolated compute units on chip. So for each of the 384/3=128 physical ALUs there are 181 registers available (aka the value `RegCount`) at most. The illustration in the figure is somehow confusing and I would apologize about that.

------

Other things you might want to know:

> In addition, according to the following sections, we can know that nreg_max will not exceed 512.

It's just a random number so that the tests don't take too much time to run.

> According to [adreno640/Google_Pixel_4/ArchProbeReport.json](https://github.com/microsoft/ArchProbe/blob/main/examples/adreno640/Google_Pixel_4/ArchProbeReport.json#L71), Does this mean "It shows a 24×183 shared 32b-register pool."？

`FullRegConcurWorkgroupCount` and `HalfRegConcurWorkgroupCount` are only used to decide whether register allocation has an impact on workgroup scheduling. If yes, the number of concurrent threads decreases as the number of register occupation increases, i.e., the registerd are pooled, shared among concurrent warps. Otherwise, using more or less registers wouldn't change the number of concurrent warps. Please refer to my paper for more detail.

**Comment by i-Taozi** [comment]
First of all thank you very much for your answer！

At the same time, I would like to thank you all for your contributions in this field, which gave me the opportunity to learn more about mobile GPUs. 

This paper and ArchProbe are of great significance. I will continue to study this and hope to have the opportunity to communicate with you in the future.

Have a good day!

**Comment by PENGUINLIONG** [comment]
Thank you for your appreciation. g day. :)
